const store = {
  "data": [
      {
          "id": 102,
          "creation_date": "30 Apr 2021 10:35",
          "title": null,
          "image": "https://voxiot.com/images/news/",
          "content": null,
          "author": 3,
          "author_name": "Candido Waelchi",
          "author_email": "newton01@example.net",
          "author_photo": "https://voxiot.com/images/users/12.jpg",
          "author_registration_date": "08 Feb 1998 13:19"
      },
      {
          "id": 99,
          "creation_date": "30 Apr 2021 10:34",
          "title": null,
          "image": "https://voxiot.com/images/news/",
          "content": null,
          "author": 3,
          "author_name": "Candido Waelchi",
          "author_email": "newton01@example.net",
          "author_photo": "https://voxiot.com/images/users/12.jpg",
          "author_registration_date": "08 Feb 1998 13:19"
      },
      {
          "id": 15,
          "creation_date": "29 Sep 2001 15:58",
          "title": "Consectetur velit aut molestiae at.",
          "image": "https://voxiot.com/images/news/63.jpg",
          "content": "Quos qui est quis eum exercitationem. Veritatis dolor excepturi facilis eligendi. Eveniet iure magni aut cum dolorem rerum. Sunt expedita qui id facilis rerum molestiae ut voluptatem.",
          "author": 78,
          "author_name": "Harmon Paucek",
          "author_email": "considine.kenya@example.net",
          "author_photo": "https://voxiot.com/images/users/61.jpg",
          "author_registration_date": "22 Aug 1986 17:25"
      },
      {
          "id": 86,
          "creation_date": "07 May 1984 16:43",
          "title": "Vero vel eaque sequi.",
          "image": "https://voxiot.com/images/news/16.jpg",
          "content": "Repellendus nostrum ipsum error aut eum fugiat rem. Est provident quia maxime consequuntur illum dolore. Et labore aut temporibus.",
          "author": 43,
          "author_name": "Ms. Gisselle Grimes Jr.",
          "author_email": "jgerhold@example.org",
          "author_photo": "https://voxiot.com/images/users/4.jpg",
          "author_registration_date": "10 Oct 1996 03:01"
      },
      {
          "id": 54,
          "creation_date": "24 Jun 1981 05:00",
          "title": "Nesciunt aut accusantium.",
          "image": "https://voxiot.com/images/news/4.jpg",
          "content": "Eos hic similique amet reprehenderit architecto consequatur. Dolore distinctio voluptates rerum inventore molestiae sit id. Minus aut alias dolore quos.",
          "author": 54,
          "author_name": "Mrs. Madisyn Wunsch",
          "author_email": "jarrell98@example.net",
          "author_photo": "https://voxiot.com/images/users/10.jpg",
          "author_registration_date": "14 Jun 2006 10:56"
      },
      {
          "id": 71,
          "creation_date": "05 Oct 1971 20:14",
          "title": "Quia molestiae ut non.",
          "image": "https://voxiot.com/images/news/10.jpg",
          "content": "Quod et repellat recusandae. Est quam id et laudantium. Totam unde dolorum consectetur aut. Enim nihil deleniti velit similique.",
          "author": 78,
          "author_name": "Harmon Paucek",
          "author_email": "considine.kenya@example.net",
          "author_photo": "https://voxiot.com/images/users/61.jpg",
          "author_registration_date": "22 Aug 1986 17:25"
      },
      {
          "id": 42,
          "creation_date": "30 Apr 2012 23:00",
          "title": "Repudiandae eos similique eligendi aut.",
          "image": "https://voxiot.com/images/news/44.jpg",
          "content": "At eveniet est ut quis expedita voluptas veniam earum. Dolorem optio suscipit omnis velit. Dicta recusandae illo incidunt. Architecto quas vero earum itaque explicabo quos.",
          "author": 67,
          "author_name": "Kaylin Wunsch",
          "author_email": "bhaley@example.net",
          "author_photo": "https://voxiot.com/images/users/46.jpg",
          "author_registration_date": "03 Aug 1985 04:44"
      },
      {
          "id": 2,
          "creation_date": "17 Jan 1997 20:53",
          "title": "Quia non magnam eaque dolores.",
          "image": "https://voxiot.com/images/news/42.jpg",
          "content": "Voluptatum et totam in est animi. Id modi laudantium itaque repudiandae et nam. Itaque magni voluptas at natus.",
          "author": 61,
          "author_name": "Dr. Kayla Barrows IV",
          "author_email": "wtreutel@example.net",
          "author_photo": "https://voxiot.com/images/users/38.jpg",
          "author_registration_date": "21 Jan 1985 23:03"
      },
      {
          "id": 5,
          "creation_date": "03 Feb 1974 02:55",
          "title": "Atque autem reprehenderit.",
          "image": "https://voxiot.com/images/news/62.jpg",
          "content": "Ipsa est et non velit minima. Est eum in nemo. Rem soluta expedita sint fuga incidunt maiores.",
          "author": 5,
          "author_name": "Libby Feest DVM",
          "author_email": "wilburn98@example.com",
          "author_photo": "https://voxiot.com/images/users/82.jpg",
          "author_registration_date": "27 Nov 1983 09:29"
      },
      {
          "id": 36,
          "creation_date": "27 Sep 2002 02:26",
          "title": "Suscipit magni maiores.",
          "image": "https://voxiot.com/images/news/28.jpg",
          "content": "Incidunt quis dicta quidem mollitia nesciunt sint consequatur. Facere ut perspiciatis molestiae nihil. Dolorem ea ipsam maxime inventore. Et ipsam vel ut dolor beatae.",
          "author": 65,
          "author_name": "Miss Wava Kemmer III",
          "author_email": "golda66@example.net",
          "author_photo": "https://voxiot.com/images/users/60.jpg",
          "author_registration_date": "08 Apr 1985 23:49"
      },
      {
          "id": 35,
          "creation_date": "02 May 2001 10:12",
          "title": "Fugit optio fuga.",
          "image": "https://voxiot.com/images/news/2.jpg",
          "content": "Enim omnis vel qui rem impedit qui expedita. Ut perspiciatis nobis illum nihil ut. Est maxime eveniet velit ut.",
          "author": 25,
          "author_name": "Leslie Adams III",
          "author_email": "chadd42@example.org",
          "author_photo": "https://voxiot.com/images/users/87.jpg",
          "author_registration_date": "24 Sep 2008 22:11"
      },
      {
          "id": 59,
          "creation_date": "02 Jan 2010 09:23",
          "title": "Quo dicta culpa.",
          "image": "https://voxiot.com/images/news/32.jpg",
          "content": "Hic asperiores exercitationem architecto delectus omnis voluptatibus et. Rerum natus impedit qui veritatis.",
          "author": 57,
          "author_name": "Reese Stiedemann",
          "author_email": "monahan.aidan@example.org",
          "author_photo": "https://voxiot.com/images/users/18.jpg",
          "author_registration_date": "30 Mar 2012 06:13"
      },
      {
          "id": 27,
          "creation_date": "20 Sep 1978 08:42",
          "title": "Omnis perferendis voluptatem et.",
          "image": "https://voxiot.com/images/news/81.jpg",
          "content": "Mollitia nostrum rem ut ab quam ea quibusdam. Aut iste delectus iure aspernatur esse. Ut vero repellat laudantium qui at. Dolorum unde omnis molestiae veritatis eum repellat.",
          "author": 37,
          "author_name": "Coralie McCullough",
          "author_email": "hoeger.kenyon@example.net",
          "author_photo": "https://voxiot.com/images/users/85.jpg",
          "author_registration_date": "25 Jun 1988 14:48"
      },
      {
          "id": 12,
          "creation_date": "20 Aug 2016 06:14",
          "title": "Possimus voluptas quos mollitia.",
          "image": "https://voxiot.com/images/news/40.jpg",
          "content": "Vitae neque eligendi qui beatae. Numquam consequuntur tempore natus et consequuntur error nulla exercitationem. Dolor autem aut molestias soluta vel neque.",
          "author": 79,
          "author_name": "Chyna Schultz",
          "author_email": "franecki.etha@example.com",
          "author_photo": "https://voxiot.com/images/users/65.jpg",
          "author_registration_date": "06 Jun 1984 08:31"
      },
      {
          "id": 83,
          "creation_date": "01 Sep 1973 01:04",
          "title": "Cum rem.",
          "image": "https://voxiot.com/images/news/50.jpg",
          "content": "Amet et velit cum non. Harum quae pariatur porro non. Est minima veniam in placeat aut et. Officia dolor temporibus non eos praesentium repudiandae.",
          "author": 50,
          "author_name": "Agustin Russel",
          "author_email": "jamey.daugherty@example.com",
          "author_photo": "https://voxiot.com/images/users/5.jpg",
          "author_registration_date": "25 Jun 2006 04:04"
      },
      {
          "id": 13,
          "creation_date": "15 Feb 1998 01:20",
          "title": "Modi fugit sunt.",
          "image": "https://voxiot.com/images/news/75.jpg",
          "content": "Dolores sequi ex vel quaerat consequatur. Labore illo debitis quod voluptatibus sequi. Nam ipsa incidunt dolore est accusantium et aut.",
          "author": 48,
          "author_name": "Donato Jerde",
          "author_email": "ksmitham@example.net",
          "author_photo": "https://voxiot.com/images/users/48.jpg",
          "author_registration_date": "23 Oct 2018 00:59"
      },
      {
          "id": 11,
          "creation_date": "21 Feb 1996 11:34",
          "title": "Animi ducimus blanditiis.",
          "image": "https://voxiot.com/images/news/51.jpg",
          "content": "Deleniti nam iusto voluptatem in nihil incidunt possimus. Ut et architecto id. Sapiente in doloremque voluptatem quam. Fugiat fugit a ut rerum modi minima doloribus.",
          "author": 58,
          "author_name": "Cynthia Rath",
          "author_email": "ahegmann@example.com",
          "author_photo": "https://voxiot.com/images/users/42.jpg",
          "author_registration_date": "20 Jun 2019 18:43"
      },
      {
          "id": 61,
          "creation_date": "16 Feb 1981 09:07",
          "title": "Voluptates quos nobis.",
          "image": "https://voxiot.com/images/news/18.jpg",
          "content": "Dolor rerum non minus eum maxime nihil itaque eaque. Autem doloribus eum modi dignissimos sed. Voluptatem cum incidunt fuga facilis. Ullam eaque est accusamus maxime ut amet.",
          "author": 61,
          "author_name": "Dr. Kayla Barrows IV",
          "author_email": "wtreutel@example.net",
          "author_photo": "https://voxiot.com/images/users/38.jpg",
          "author_registration_date": "21 Jan 1985 23:03"
      },
      {
          "id": 44,
          "creation_date": "20 Apr 2014 01:57",
          "title": "Cum qui eos et.",
          "image": "https://voxiot.com/images/news/86.jpg",
          "content": "Autem sed dicta aperiam. Corrupti sed tenetur nam dolorem dolorem. Autem sequi voluptatem quibusdam aut doloribus eum. Et aliquid nostrum omnis tempore odit.",
          "author": 72,
          "author_name": "Melody Toy",
          "author_email": "koch.reyes@example.org",
          "author_photo": "https://voxiot.com/images/users/27.jpg",
          "author_registration_date": "01 Nov 1977 00:51"
      },
      {
          "id": 21,
          "creation_date": "20 May 1974 11:11",
          "title": "Deleniti ullam laudantium ducimus.",
          "image": "https://voxiot.com/images/news/9.jpg",
          "content": "Eum illo nihil ducimus quis aliquam. Repellat nam laudantium sunt qui commodi. Ducimus voluptatem minus eum est. Dicta animi sit asperiores quo id totam.",
          "author": 54,
          "author_name": "Mrs. Madisyn Wunsch",
          "author_email": "jarrell98@example.net",
          "author_photo": "https://voxiot.com/images/users/10.jpg",
          "author_registration_date": "14 Jun 2006 10:56"
      }
  ],
  "page": 1,
  "pages": 6
}

export default store;